# File @generated by hack/generate-authors.sh. DO NOT EDIT.
# This file lists all contributors to the repository.
# See hack/generate-authors.sh to make modifications.

Oscar Morell <oscarmorell07@yahoo.com>
Juan Silva <juansilva.dvm@gmail.com>
